import { z } from "zod";

import {
  zClaimOut,
  zComposerDetail,
  zComposerPage,
  zComposerSummary,
  zComposerWorkOut,
  zComposerWorksPage,
  zWorkProofOut,
} from "./generated/zod.gen";

// The consumer API's contract is generated from its OpenAPI schema (dumped from
// the FastAPI app into openapi.json). `zod.gen.ts` is generated by
// @hey-api/openapi-ts — do not edit it; run `npm run gen` after changing the
// API's Pydantic models. This module re-exports the generated schemas under the
// names the app uses (the claim model is `ClaimOut` upstream) so api.ts and the
// pages need not know about the generator, and api.ts still `parse()`s every
// response so malformed data fails loudly instead of rendering garbage.

export const ComposerSummarySchema = zComposerSummary;
export const ComposerPageSchema = zComposerPage;
export const ClaimSchema = zClaimOut;
export const ComposerDetailSchema = zComposerDetail;
export const WorkProofSchema = zWorkProofOut;
export const ComposerWorkSchema = zComposerWorkOut;
export const ComposerWorksPageSchema = zComposerWorksPage;

export type ComposerSummary = z.infer<typeof ComposerSummarySchema>;
export type ComposerPage = z.infer<typeof ComposerPageSchema>;
export type Claim = z.infer<typeof ClaimSchema>;
export type ComposerDetail = z.infer<typeof ComposerDetailSchema>;
export type WorkProof = z.infer<typeof WorkProofSchema>;
export type ComposerWork = z.infer<typeof ComposerWorkSchema>;
export type ComposerWorksPage = z.infer<typeof ComposerWorksPageSchema>;
