"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-08-23 23:30:35.706603

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("canonical_entity_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "dedup_key", name="uq_entity_kind_key"),
    )
    op.create_index("ix_entities_canonical", "entities", ["canonical_entity_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "concerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_key", sa.Text(), nullable=False),
        sa.Column("date", sa.Text(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("season", sa.String(length=50), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_key", name="uq_concert_source_key"),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_seen", sa.Integer(), nullable=False),
        sa.Column("records_new", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_entity_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "canonical_entity_id", name="uq_person_match"),
    )
    op.create_index("ix_person_matches_status", "person_matches", ["status"], unique=False)
    op.create_table(
        "recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_key", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("catalogue_number", sa.Text(), nullable=True),
        sa.Column("format", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_key", name="uq_recording_source_key"),
    )
    op.create_table(
        "works",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("composer_entity_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_title", sa.Text(), nullable=False),
        sa.Column("title_key", sa.Text(), nullable=False),
        sa.Column("work_type", sa.String(length=100), nullable=True),
        sa.Column("opus_number", sa.String(length=50), nullable=True),
        sa.Column("catalogue_prefix", sa.String(length=20), nullable=True),
        sa.Column("catalogue_number", sa.String(length=50), nullable=True),
        sa.Column("musical_key", sa.String(length=50), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["composer_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_works_composer", "works", ["composer_entity_id"], unique=False)
    op.create_table(
        "concert_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concert_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("discipline", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concert_id"],
            ["concerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_concert_participants_concert", "concert_participants", ["concert_id"], unique=False)
    op.create_index("ix_concert_participants_entity", "concert_participants", ["entity_id"], unique=False)
    op.create_table(
        "entity_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_run_id", sa.Integer(), nullable=False),
        sa.Column("last_run_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_run_id"],
            ["ingest_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_run_id"],
            ["ingest_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_source_external"),
    )
    op.create_index("ix_entity_records_entity_id", "entity_records", ["entity_id"], unique=False)
    op.create_table(
        "raw_work_mentions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("raw_composer", sa.Text(), nullable=True),
        sa.Column("raw_title", sa.Text(), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.Column("composer_entity_id", sa.Uuid(), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("match_status", sa.String(length=20), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("match_method", sa.String(length=50), nullable=True),
        sa.Column("candidate_work_id", sa.Uuid(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_run_id", sa.Integer(), nullable=False),
        sa.Column("last_run_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_work_id"],
            ["works.id"],
        ),
        sa.ForeignKeyConstraint(
            ["composer_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_run_id"],
            ["ingest_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_run_id"],
            ["ingest_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_mention_source_external"),
    )
    op.create_index("ix_mentions_status", "raw_work_mentions", ["match_status"], unique=False)
    op.create_index("ix_mentions_work", "raw_work_mentions", ["work_id"], unique=False)
    op.create_table(
        "recording_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("discipline", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_recording_participants_entity", "recording_participants", ["entity_id"], unique=False)
    op.create_index(
        "ix_recording_participants_recording", "recording_participants", ["recording_id"], unique=False
    )
    op.create_table(
        "work_titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_key", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_id", "title_key", "source_id", name="uq_work_title"),
    )
    op.create_index("ix_work_titles_work", "work_titles", ["work_id"], unique=False)
    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("predicate", sa.String(length=100), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["entity_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_claims_predicate_object", "claims", ["predicate", "object_id"], unique=False)
    op.create_index("ix_claims_subject_predicate", "claims", ["subject_id", "predicate"], unique=False)
    op.create_table(
        "concert_works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concert_id", sa.Integer(), nullable=False),
        sa.Column("mention_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concert_id"],
            ["concerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mention_id"],
            ["raw_work_mentions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_concert_works_concert", "concert_works", ["concert_id"], unique=False)
    op.create_table(
        "recording_works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column("mention_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mention_id"],
            ["raw_work_mentions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_recording_works_recording", "recording_works", ["recording_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recording_works_recording", table_name="recording_works")
    op.drop_table("recording_works")
    op.drop_index("ix_concert_works_concert", table_name="concert_works")
    op.drop_table("concert_works")
    op.drop_index("ix_claims_subject_predicate", table_name="claims")
    op.drop_index("ix_claims_predicate_object", table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_work_titles_work", table_name="work_titles")
    op.drop_table("work_titles")
    op.drop_index("ix_recording_participants_recording", table_name="recording_participants")
    op.drop_index("ix_recording_participants_entity", table_name="recording_participants")
    op.drop_table("recording_participants")
    op.drop_index("ix_mentions_work", table_name="raw_work_mentions")
    op.drop_index("ix_mentions_status", table_name="raw_work_mentions")
    op.drop_table("raw_work_mentions")
    op.drop_index("ix_entity_records_entity_id", table_name="entity_records")
    op.drop_table("entity_records")
    op.drop_index("ix_concert_participants_entity", table_name="concert_participants")
    op.drop_index("ix_concert_participants_concert", table_name="concert_participants")
    op.drop_table("concert_participants")
    op.drop_index("ix_works_composer", table_name="works")
    op.drop_table("works")
    op.drop_table("recordings")
    op.drop_index("ix_person_matches_status", table_name="person_matches")
    op.drop_table("person_matches")
    op.drop_table("ingest_runs")
    op.drop_table("concerts")
    op.drop_table("sources")
    op.drop_index("ix_entities_canonical", table_name="entities")
    op.drop_table("entities")
    # ### end Alembic commands ###
